# ASSIGNMENT 02: Data Structures, Functions, Numpy & Pandas

Section A: Data Structures & Control Structures


1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [4]:
num = [1,2,3,4,5]
num

[1, 2, 3, 4, 5]

In [5]:
#Append
num.append(6)
num

[1, 2, 3, 4, 5, 6]

In [8]:
#Extend
num.extend([7,8])
num

[1, 2, 3, 4, 5, 6, 7, 8, 7, 8]

In [9]:
#Insert
num.insert(4,5)
num

[1, 2, 3, 4, 5, 5, 6, 7, 8, 7, 8]

In [12]:
#Remove
num.remove(7)
num

[1, 2, 3, 4, 5, 5, 6, 8, 7, 8]

In [20]:
#Index
num.index(2)
num

[1, 2, 3, 4, 5, 5]

In [22]:
num.count(4)
num

[1, 2, 3, 4, 5, 5]

In [23]:
num.sort()
num

[1, 2, 3, 4, 5, 5]

In [24]:
num.reverse()
num

[5, 5, 4, 3, 2, 1]

In [25]:
num.clear()
num

[]

2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [26]:
students = ("Jack","Peter","Antonio")
students

('Jack', 'Peter', 'Antonio')

In [29]:
students[1] = "John"

TypeError: 'tuple' object does not support item assignment


3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [30]:
set = {1,2,3,4,4,5,5,6,7}
set

{1, 2, 3, 4, 5, 6, 7}

* Sets automatically eliminate duplicates.
* Printing a set shows only unique elements.

4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [31]:
person = {"name":"Pratham","age":"24","city":"Bangalore"}
person

{'name': 'Pratham', 'age': '24', 'city': 'Bangalore'}

In [34]:
person["age"] = 23
person

{'name': 'Pratham', 'age': 23, 'city': 'Bangalore'}

In [35]:
person = {"name":"Pratham","age":"24","city":"Bangalore","email":"pratham@xmail.com"}
person

{'name': 'Pratham',
 'age': '24',
 'city': 'Bangalore',
 'email': 'pratham@xmail.com'}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [38]:
age = int(input("Enter the age:"))
print("Age is:",age)
if age >= 18:
    print("This person is eligible to vote")
else:
    print("This person is not eligible to vote")

Age is: 25
This person is eligible to vote



6. Given a 'marks' variable, print the grade:
* 90 and above: 'A'
* 75–89: 'B'
* 50–74: 'C'
* Below 50: 'Fail'

In [40]:
marks = int(input("Enter the Marks:"))
print("Marks are:",marks)
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Marks are: 77
Grade: B


7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [41]:
num =  int(input("Enter a number:"))
print("Entered number:",num)
if num > 0:
    if num % 2 == 0:
        print("Number is positive Even")
    else:
        print("Number is Positive Odd")
elif num == 0:
    print("Number is Zero")
else:
    print("Number is Negative")

Entered number: 4
Number is positive Even


# Section B: Numpy

8. Create:
* scalar using np.array(5)
* 1D array with values 1 to 5
* 2D array (2x3) with values from 10 to 60 in steps of 10

In [42]:
import numpy as np

In [43]:
scalar = np.array(5)
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[10,20,30],[40,50,60]])

In [44]:
scalar

array(5)

In [45]:
arr1

array([1, 2, 3, 4, 5])

In [46]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [48]:
import numpy as np
import random

In [49]:
ran = np.random.randint(0,100,(4,4))
ran

array([[64,  4, 47, 28],
       [58, 29, 43, 94],
       [45, 21, 89, 54],
       [38, 70,  8, 33]], dtype=int32)

10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [50]:
import pandas as pd

In [52]:
arr = np.arange(11,20).reshape(3,3)
arr

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [53]:
df = pd.DataFrame(arr, columns=['A','B','C'])
df

A   B   C
0  11  12  13
1  14  15  16
2  17  18  19

# Section C: Exploring Pandas

11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
* Use .info(), .describe()
* Select 'Name' and 'City' columns
* Drop 'City' column
* Fill any missing values in 'Salary' column with the mean
* Remove any duplicate rows

In [54]:
import pandas as pd

In [105]:
data = {
    "Name":["Philbert","Sakshi","Omkar","Samyak","Aman","Aneesh","Omkar","Rohan","Pratham","Aman"],
    "Age":[25,21,26,23,25,28,26,25,29,30],
    "City":["Belgaum","Bangalore","Mumbai","Bangalore","Delhi","Mumbai","Mumbai","Delhi","Mumbai","Pune"],
    "Salary":[50000,45000,60000,None,72000,59000,60000,None,40000,50000]
}

In [106]:
df_data = pd.DataFrame(data)
df_data

Name  Age       City   Salary
0  Philbert   25    Belgaum  50000.0
1    Sakshi   21  Bangalore  45000.0
2     Omkar   26     Mumbai  60000.0
3    Samyak   23  Bangalore      NaN
4      Aman   25      Delhi  72000.0
5    Aneesh   28     Mumbai  59000.0
6     Omkar   26     Mumbai  60000.0
7     Rohan   25      Delhi      NaN
8   Pratham   29     Mumbai  40000.0
9      Aman   30       Pune  50000.0

In [107]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [108]:
df_data.describe()

Age        Salary
count  10.000000      8.000000
mean   25.800000  54500.000000
std     2.699794  10198.039027
min    21.000000  40000.000000
25%    25.000000  48750.000000
50%    25.500000  54500.000000
75%    27.500000  60000.000000
max    30.000000  72000.000000

In [109]:
df_data[["Name","City"]]

Name       City
0  Philbert    Belgaum
1    Sakshi  Bangalore
2     Omkar     Mumbai
3    Samyak  Bangalore
4      Aman      Delhi
5    Aneesh     Mumbai
6     Omkar     Mumbai
7     Rohan      Delhi
8   Pratham     Mumbai
9      Aman       Pune

In [110]:
df = df_data.drop("City",axis=1)
df

Name  Age   Salary
0  Philbert   25  50000.0
1    Sakshi   21  45000.0
2     Omkar   26  60000.0
3    Samyak   23      NaN
4      Aman   25  72000.0
5    Aneesh   28  59000.0
6     Omkar   26  60000.0
7     Rohan   25      NaN
8   Pratham   29  40000.0
9      Aman   30  50000.0

In [111]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

Name  Age   Salary
0  Philbert   25  50000.0
1    Sakshi   21  45000.0
2     Omkar   26  60000.0
3    Samyak   23  54500.0
4      Aman   25  72000.0
5    Aneesh   28  59000.0
6     Omkar   26  60000.0
7     Rohan   25  54500.0
8   Pratham   29  40000.0
9      Aman   30  50000.0

In [112]:
df.drop_duplicates()

Name  Age   Salary
0  Philbert   25  50000.0
1    Sakshi   21  45000.0
2     Omkar   26  60000.0
3    Samyak   23  54500.0
4      Aman   25  72000.0
5    Aneesh   28  59000.0
7     Rohan   25  54500.0
8   Pratham   29  40000.0
9      Aman   30  50000.0